name = "seu-status"
main = "src/index.ts"
compatibility_date = "2025-02-14"

[triggers]
crons = ["*/1 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "seu-status-db"
database_id = "0a83f2aa-c2a9-4a72-9122-b1bde88c2fd9"

[vars]
VAPID_SUBJECT = "mailto:admin@y3f.me"

# Secrets (set via `wrangler secret put`):
# TELEGRAM_BOT_TOKEN
# TELEGRAM_CHAT_ID (use @seu_status for channel)
# VAPID_PUBLIC_KEY
# VAPID_PRIVATE_KEY
